source 'https://github.com/CocoaPods/Specs.git'

swift_version = “4.0”
platform :ios, ’11.2’
use_frameworks!


target ‘SuperBkk’ do
    pod 'Reachability'
    pod 'Alamofire’
    pod 'PromiseKit'
end

